[package]
name = "gerador_de_senhas_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
actix-web = "4"
actix-files = "0.6"
actix-cors = "0.6"        
serde = { version = "1.0", features = ["derive"] }
